.gitignore
package.json
src/App.js
src/App.test.js
src/components/course-page.js
src/components/home-page.js
src/components/review-page.js
yarn.lock

Elec 61/react router

---

src/components/review-card.js
src/pages/course-page.js
src/pages/tempCodeRunnerFile.js

wow there's two columns in the course page, and review cards are made

add basic layout for course page

---

src/components/course-review-card.js
src/components/star-ratings.js

Elec71 create cards

---

src/components/toggle-other-tags-button.js
src/pages/home-page.js

added toggle other tags button

---

src/components/review-card.js
src/components/summary-card.js
src/pages/course-page.js

added in the overall card layout for course summary, and fixed up the spacing of the cards on the course page

basic layout of course summary card and fixed spacing of course page

---

.eslintrc.json
src/index.css
src/pages/home-page.js

Added a segment for the search section

Elec 72 search section background

---

src/components/summary-card.js
src/index.css

course summary card with bar charts

---

src/pages/home-page.js

Note: The segment increasing in size will need to be revisited when everything is added.

Moved the ELEC 73 Toggle tags button into the segment

---

src/components/review-card-ratings-only.js
src/components/review-card.js
src/index.css
src/pages/course-page.js

made review card for reviews that have ratings only but no description

Elec 107 - created review card for ratings only

---

src/components/course-review-card.js
src/pages/home-page.js

Reverts csesoc/CSElectives#42
DID NOT BUILD

Revert "Elec 10 default view most popular elecs"

---

src/pages/home-page.js

Elec 10 default view most popular elecs

---

src/pages/course-page.js

- added a function getReviewDate that changes the timestamp to a readable date

added timestamp into reviews

---

src/components/course-page-tags.js
src/components/home-page-tags.js
src/components/summary-card.js
src/components/tags.js
src/pages/home-page.js

uwu owo xoxo :PPP
does anyone even see this bit
I never see this bit
Surely someone doex

Redid labels structure les go

---

src/App.js
src/pages/course-page.js
src/styles/course-page.css

- also added in the empty state (if the course has no reviews -> include "No reviews yet" and button to go back home)
also included function so that:
- if reviews have text -> use reviews card
- if reviews don't have text -> use ratings card

created routes for each course

---

src/components/dropdown-tag-menu.js
src/pages/home-page.js

This allows the tag groups to be grouped together in display. Also sorted the arrays

Separated current activeTags into three different ones

---

src/App.js
src/components/header.js
src/styles/index.css

Created the searchbar dropdown options from the courses database. Sizing still needs to be done.

Elec 144 searchbar dropdown

---

src/pages/home-page.js

so over working on these cards...

Elec 163 wrap page contents on resize

---

src/components/summary-card.js
src/pages/course-page.js

- get tags for the term that the course is available in, the prefix (i.e. COMP, SENG, etc), and its level (i.e. level 1, level 3, etc)
- displays tags at the top of the course summary

added tags into course page

---

src/components/review-card-ratings-only.js
src/components/review-card.js
src/components/summary-card.js
src/pages/course-page.js
src/styles/course-page.css
src/styles/index.css

- used dots at the top of review instead of the bars on the side
- removed topics from course summary card
- need to make space between grid.row smaller

added dots instead of bars for reviews

---

src/components/header.js
src/db/db.js

Created login modal UI with a form

Created login modal UI with a form

---

src/pages/course-page.js

* submit section is currently under the summary in the left column
* will change so that it is a modal component

restyled course page so it's one column of reviews

---

src/components/review-card.js
src/components/summary-card.js
src/pages/course-page.js
src/styles/course-page.css

* put the categories in 3 columns in review card
* restyled summary card to display numbers instead of bar chart
* still need to put submit section into modal component

restyled the summary and review cards

---

src/components/course-review-card.js
src/pages/home-page.js
src/styles/home-page.css
src/styles/index.css

Elec 205 add tag for summer term

---

src/components/course-review/placeholder-reviews.js
src/components/course-review/placeholder-summary.js
src/pages/course-page.js
src/styles/course-page.css

* created a placeholder for the summary section and one for the review cards
* there is a tinyyyy bit of inline styling for the review cards, i tried to do it without but it didn't work pls forgive me

created placeholders for when course page is loading

---

src/components/course-review/reviews-bar.js
src/components/review-card.js
src/components/summary-card.js
src/styles/course-page.css
src/styles/index.css

- removed scroll in summary section for mobile view
- split reviews bar into multiple lines instead of everything in one when in mobile view
note: the split reviews bar doesn't look the best rn lmao but it's an improvement

mobile view on course page

---

src/components/scroll-button.js

- removed it bc idk how tf to fix it so it stays at the bottom instead of the middle when its mobile view

removed scroll button when in mobile view

---

src/components/login-modal/login-modal.js
src/styles/login-page.css

- created dropdown for profile when logged in
- name appears when logged in 
- dropdown has log out as it's only option currently

Created profile and log out button

---

src/components/review-modal.js

temporary fix to keep anonymity

removed anonymity qn

---

src/components/header.js
src/components/login-modal/login-modal.js

- when in mobile view, if logged in, it will show the profile icon but without name so everything fits in the navbar
- search bar in the navbar will be on hold til next year :))

navbar mobile view

---

src/styles/home-page.css
src/styles/index.css

- fixed up font size of cselectives
- changed the blob url thing, apparently there's sometimes issues when you set an svg as a background image so i changed how we added it, idk if it will work tho
- made the body background color the slightest off white to the point u can't actually tell it isn't white lol

fixed up font size on front page

---

src/styles/home-page.css

fixed size of no results image in mobile view

---

src/components/card-grid.js
src/components/course-review-card.js
src/components/course-review/reviews-bar.js
src/components/dropdown-tag-menu.js
src/components/review-card.js
src/components/review-form/course-ratings.js
src/components/review-form/review-choice.js
src/components/review-modal.js
src/components/review-rating/review-rating.js
src/components/summary-card.js

This PR silences warnings in the console of a dev deployment.
- Fixed propType definitions
- Corrected props
- Removed incorrect types
- Added keys to lists of JSX elements

Fixed misc type warnings

---

.env
src/components/review-card.js
src/styles/course-page.css
src/verifier/verifier.js

Just made a change to the styling for review descriptions to accurately show new-line breaks.

Fixed line-breaks not appearing in review descriptions

---

src/components/footer.js

[fix] Make footer show current year
